In [1]:
import torch
import numpy as np

In [2]:
"""
        Compute importance score for a sample x, over time and features
        :param x: Sample instance to evaluate score for. Shape:[batch, features, time]
        :param n_samples: number of Monte-Carlo samples
        :return: Importance score matrix of shape:[batch, features, time]
        """
a = np.array([
    [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]],
    [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]],
    [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]],
    [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]],])
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [3]:
r = a.reshape(-1)
r

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,  1,
        2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,  1,  2,
        3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,  1,  2,  3,
        4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

### 测试FO及AFO

In [4]:
c = a.copy()
c[:, 1, 1] = np.random.uniform(-3, +3, size=(len(a),))
c

array([[[ 1,  2,  3,  4],
        [ 5,  0,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[ 1,  2,  3,  4],
        [ 5,  2,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[ 1,  2,  3,  4],
        [ 5,  1,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[ 1,  2,  3,  4],
        [ 5, -2,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [58]:
import torch
import numpy as np
T1 = torch.tensor([[[[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]],
                 [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]],
                 [[19, 20, 21],
                 [22, 23, 24],
                 [25, 26, 27]]],
                 [[[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]],
                 [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]],
                 [[19, 20, 21],
                 [22, 23, 24],
                 [25, 26, 27]]]])
print(T1.size())

torch.Size([2, 3, 3, 3])


In [61]:
a = torch.stack([x[0] for x in T1])
a.shape
a

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [62]:
b = a[:,1,:].reshape(-1)
print('b',b)
c = np.random.choice(b, size=(2,))
print('c',c)

b tensor([4, 5, 6, 4, 5, 6])
c [4 6]


In [65]:
b_all = a[:,1:,:]
# c_all = a[:,2:,:]
print(b_all,b_all.shape)

tensor([[[4, 5, 6],
         [7, 8, 9]],

        [[4, 5, 6],
         [7, 8, 9]]]) torch.Size([2, 2, 3]) tensor([[[7, 8, 9]],

        [[7, 8, 9]]])


In [66]:
b_tran = np.transpose(b_all, (0, 2, 1)).reshape(b_all.shape[0] * b_all.shape[2], -1)
# c_tran = np.transpose(c_all, (0, 2, 1)).reshape(c_all.shape[0] * c_all.shape[2], -1)
print(b_tran, b_tran.shape)

tensor([[4, 7],
        [5, 8],
        [6, 9],
        [4, 7],
        [5, 8],
        [6, 9]]) torch.Size([6, 2]) tensor([[7],
        [8],
        [9],
        [7],
        [8],
        [9]])


In [47]:
b_new = b_tran.T

tensor([[4, 5, 6, 4, 5, 6],
        [7, 8, 9, 7, 8, 9]])

In [55]:
c = b_tran[np.random.choice(b_tran.shape[0], size=3, replace=False), :]
c.T

tensor([[6, 5, 5],
        [9, 8, 8]])

In [56]:
A = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8],
              [9, 7, 6],
              [3, 2, 2],
              [0, 1, 0],
              [1, 3, 1],
              [0, 4, 1],
              [2, 4, 2],
              [3, 6, 1]])

B = A[np.random.choice(A.shape[0], size=4, replace=False), :]
print(B,A.shape[0])
print(B.T)

[[0 1 2]
 [3 6 1]
 [3 2 2]
 [3 4 5]] 10
[[0 3 3 3]
 [1 6 2 4]
 [2 1 2 5]]


In [33]:
np.array([[4, 7],
          [5, 8],
          [6, 9], 
          [4, 7],
          [5, 8],
          [6, 9]]).shape

(6, 2)

### 测试TFS

In [ ]:
class TFSExplainer:
    def __init__(self, model, train_loader, activation=torch.nn.Softmax(-1)):
        self.device = "cuda" if torch.cuda.is_available() else "cpu"
        self.base_model = model.to(self.device)
        trainset = list(train_loader.dataset)
        self.data_distribution = torch.stack([x[0] for x in trainset]) # torch.stack()，沿着一个新维度对输入向量序列进行连接，增加新的维度堆叠已有张量（2->3,3->4）
        self.activation = activation

    def attribute(self, x, y, retrospective=False):
        
        x = x.to(self.device)
        _, n_features, t_len = x.shape
        score = np.zeros(x.shape)
        if retrospective:
            p_y_t = self.activation(self.base_model(x))

        for t in range(1, t_len):
            if not retrospective:
                p_y_t = self.activation(self.base_model(x[:, :, : t + 1]))
            for i in range(n_features):
                # reshape(-1)的作用是将数组变为一维,即从多个时间点对应的相同特征进行选取
                feature_dist_z = np.array(self.data_distribution[:, i:, :])
                feature_dist_o = np.array(self.data_distribution[:, i+1:, :])
                x_hat_z = x[:, :, 0 : t + 1].clone()
                x_hat_o = x[:, :, 0 : t + 1].clone()
                kl_all = []
                for _ in range(10):
                    # 从x的训练集特征分布中采样t时刻的特征i，
                    feature_seed = np.random.randint(0,t_len,dtype='int')
                    x_hat_z[:, i:, t] = feature_dist_z[:,:,feature_seed]
                    x_hat_o[:, i+1:, t] = feature_dist_o[:,:,feature_seed]
                    y_hat_t = self.activation(self.base_model(x_hat_z))
                    y_hat_o = self.activation(self.base_model(x_hat_o))
                    # kl = torch.nn.KLDivLoss(reduction='none')(torch.log(y_hat_t), p_y_t)
                    kl = torch.abs((y_hat_t) - (y_hat_o))
                    # kl_all.append(torch.sum(kl, -1).cpu().detach().numpy())
                    kl_all.append(np.mean(kl.detach().cpu().numpy(), -1))
                E_kl = np.mean(np.array(kl_all), axis=0)
                # score[:, i, t] = 2./(1+np.exp(-1*E_kl)) - 1.
                score[:, i, t] = E_kl
        return score

In [46]:
import numpy as np

# 生成一个3x4x5的随机三维数组
arr = np.random.rand(3, 4, 5)

# 随机抽取一个二维数组
dim = np.random.randint(0, 5)
sub_arr = arr[:,:,dim]

print(sub_arr)


[[0.84225097 0.67060092 0.7458979  0.20037179]
 [0.33706542 0.46889425 0.56240141 0.22768581]
 [0.42327018 0.36010712 0.37087937 0.7257854 ]]


In [7]:
x_o = a[:,:,0:2].copy()
z_o = a[:,:,np.random.randint(0, a.shape[1], dtype='int')].copy()
print(x_o.shape)
print(z_o.shape)
print(x_o)
print(z_o)

(4, 4, 2)
(4, 4)
[[[ 1  2]
  [ 5  6]
  [ 9 10]
  [13 14]]

 [[ 1  2]
  [ 5  6]
  [ 9 10]
  [13 14]]

 [[ 1  2]
  [ 5  6]
  [ 9 10]
  [13 14]]

 [[ 1  2]
  [ 5  6]
  [ 9 10]
  [13 14]]]
[[ 3  7 11 15]
 [ 3  7 11 15]
 [ 3  7 11 15]
 [ 3  7 11 15]]


In [8]:
x_o[:,3:,-1] = z_o[:,3:]
x_with_j = x_o
print('x_with_j',x_with_j)
print('x_o',x_o)
x_o[:,2:,-1] = z_o[:,2:]
x_no_j = x_o
print('x_no_j',x_no_j)
print('x_o',x_o)

x_with_j [[[ 1  2]
  [ 5  6]
  [ 9 10]
  [13 15]]

 [[ 1  2]
  [ 5  6]
  [ 9 10]
  [13 15]]

 [[ 1  2]
  [ 5  6]
  [ 9 10]
  [13 15]]

 [[ 1  2]
  [ 5  6]
  [ 9 10]
  [13 15]]]
x_o [[[ 1  2]
  [ 5  6]
  [ 9 10]
  [13 15]]

 [[ 1  2]
  [ 5  6]
  [ 9 10]
  [13 15]]

 [[ 1  2]
  [ 5  6]
  [ 9 10]
  [13 15]]

 [[ 1  2]
  [ 5  6]
  [ 9 10]
  [13 15]]]
x_no_j [[[ 1  2]
  [ 5  6]
  [ 9 11]
  [13 15]]

 [[ 1  2]
  [ 5  6]
  [ 9 11]
  [13 15]]

 [[ 1  2]
  [ 5  6]
  [ 9 11]
  [13 15]]

 [[ 1  2]
  [ 5  6]
  [ 9 11]
  [13 15]]]
x_o [[[ 1  2]
  [ 5  6]
  [ 9 11]
  [13 15]]

 [[ 1  2]
  [ 5  6]
  [ 9 11]
  [13 15]]

 [[ 1  2]
  [ 5  6]
  [ 9 11]
  [13 15]]

 [[ 1  2]
  [ 5  6]
  [ 9 11]
  [13 15]]]


In [ ]:
t_len = 4
n_features = 4
n_samples = 3
for t in range(1, t_len):

            for i in range(n_features):
                div_all=[]
                x_o = a[:,:,0:t+1].copy()
                for _ in range(n_samples):
                    z_o = a[:,:,np.random.randint(0, a.shape[1], dtype='int')].copy()
                    x_o[:,i+1:,t] = z_o[:,i+1:]
                    x_with_j = x_o
                    x_o[:,i:,t] = z_o[:,i:]
                    x_no_j = x_o

In [ ]:
class TFS:
    def __init__(self, model, activation=torch.nn.Softmax(-1)):
        self.device = 'cuda' if torch.cuda.is_available() else 'cpu'
        self.base_model = model.to(self.device)
        self.activation = activation

    def attribute(self, x, y, n_samples=10, distance_metric='kl'):
        """
        Compute importance score for a sample x, over time and features
        :param x: Sample instance to evaluate score for. Shape:[batch, features, time]
        :param n_samples: number of Monte-Carlo samples
        :return: Importance score matrix of shape:[batch, features, time]
        """
        x = x.to(self.device)
        _, n_features, t_len = x.shape
        score = np.zeros(list(x.shape))

        for t in range(1, t_len):

            for i in range(n_features):
                div_all=[]
                x_o = x[:,:,0:t+1].clone()
                # gap = 5
                # low = (t - gap) if (t - gap) > 0 else 0
                # high = (t + gap) if (t + gap) < x.shape[2] else x.shape[2]
                # for _ in range(n_samples):
                #     range_list = np.random.randint(low, high, dtype='int')
                #     z_o = x[:,:,range_list].clone()
                for _ in range(n_samples):
                    z_o = x[:,:,np.random.randint(0, x.shape[2], dtype='int')].clone()
                    x_o[:,i+1:,t] = z_o[:,i+1:]
                    x_with_j = x_o
                    x_o[:,i:,t] = z_o[:,i:]
                    x_no_j = x_o
                    y_with_j = self.activation(self.base_model(x_with_j))
                    y_no_j = self.activation(self.base_model(x_no_j))
                    div = torch.abs(y_with_j-y_no_j)
                    div_all.append(np.mean(div.detach().cpu().numpy(), -1))
                E_div = np.mean(np.array(div_all),axis=0)
                score[:, i, t] = E_div
        return score

### 测试MIMIC数据上的TFS

In [ ]:
import abc
import logging
class BaseExplainer(abc.ABC):
    """
    A base class for explainer.
    """

    def __init__(self, device=None):
        """
        Constructor.

        Args:
            device:
               The torch device.
        """
        self.base_model: TorchModel | None = None
        self.device = resolve_device(device)

    @abc.abstractmethod
    def attribute(self, x):
        """
        The attribution method that the explainer will give.
        Args:
            x:
                The input tensor.

        Returns:
            The attribution with respect to x. The shape should be the same as x, or it could
            be one dimension greater than x if there is aggregation needed.

        """

    def train_generators(
        self, train_loader, valid_loader, num_epochs=300
    ) -> GeneratorTrainingResults | None:
        """
        If the explainer or attribution method needs a generator, this will train the generator.

        Args:
            train_loader:
                The dataloader for training
            valid_loader:
                The dataloader for validation.
            num_epochs:
                The number of epochs.

        Returns:
            The training results for the generator, if applicable. This includes the
            training curves.

        """
        return None

    def test_generators(self, test_loader) -> float | None:
        """
        If the explainer or attribution method needs a generator, this will return the performance
        of the generator on the test set.

        Args:
            test_loader:
                The dataloader for testing.

        Returns:
            The test result (MSE) for the generator, if applicable.

        """
        return None

    def load_generators(self) -> None:
        """
        If the explainer or attribution method needs a generator, this will load the generator from
        the disk.
        """

    def set_model(self, model, set_eval=True) -> None:
        """
        Set the base model the explainer wish to explain.

        Args:
            model:
                The base model.
            set_eval:
                Indicating whether we set to eval mode for the explainer. Note that in some cases
                like Dynamask or FIT, they do not set the model to eval mode.
        """
        self.base_model = model
        if set_eval:
            self.base_model.eval()
        self.base_model.to(self.device)

    @abc.abstractmethod
    def get_name(self):
        """
        Return the name of the explainer.
        """

In [ ]:
class TFSExplainer(BaseExplainer):

    def __init__(self, device, n_samples=10, **kwargs):
        super().__init__(device)
        self.n_samples = n_samples
        if len(kwargs) > 0:
            log = logging.getLogger(TFSExplainer.__name__)
            log.warning(f"kwargs is not empty. Unused kwargs={kwargs}")

    def attribute(self, x):
        """
        Compute importance score for a sample x, over time and features
        :param x: Sample instance to evaluate score for. Shape:[batch, features, time]
        :param n_samples: number of Monte-Carlo samples
        :return: Importance score matrix of shape:[batch, features, time]
        """
        self.base_model.eval()
        self.base_model.zero_grad()

        x = x.to(self.device)
        _, n_features, t_len = x.shape
        score = np.zeros(list(x.shape))

        for t in range(1, t_len):

            for i in range(n_features):
                div_all=[]
                x_o = x[:,:,0:t+1].clone()
                for _ in range(self.n_samples):
                    z_o = x[:,:,np.random.randint(0, x.shape[1], dtype='int')].clone()
                    x_o[:,i+1:,t] = z_o[:,i+1:]
                    x_with_j = x_o
                    x_o[:,i:,t] = z_o[:,i:]
                    x_no_j = x_o
                    y_with_j = self.base_model.predict(self.base_model(x_with_j))
                    y_no_j = self.base_model.predict(self.base_model(x_no_j))
                    div = torch.abs(y_with_j-y_no_j)
                    div_all.append(np.mean(div.detach().cpu().numpy(), -1))
                E_div = np.mean(np.array(div_all),axis=0)
                score[:, i, t] = E_div
        return score

    def get_name(self):
        if self.n_samples != 10:
            return f"tfs_sample_{self.n_samples}"
        return "tfs"